config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#top'
  get 'about' => 'users#about'

  get 'favorites/create'
  get 'favorites/destroy'

  get 'entries' => 'entries#index'
  get 'entries/show'

  resources :blogs

  resources :users, only: [:show, :edit, :index, :update, :destroy]
  resources :blogs do
       member do
       resources :entries, only: [:index, :show]
  end

  resources :entries do
       resources :favorites, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many :entries, dependent: :destroy
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :blog
  has_many :favorites, dependent: :destroy

  def favorite_user(user_id)
    favorites.find_by(user_id: user_id)
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :entry, counter_cache: :favorites_count, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :favorites, foreign_key: :user_id, dependent: :destroy
  has_many :entries, through: :favorites
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(id: resource.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_blog
    @blog = Blog.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def blog_params
    params.require(:blog).permit(:name, :url, :description)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    @entries = Entry.page(params[:page]).reverse_order
    to    = Time.now.end_of_day
    from  = (to - 6.day).beginning_of_day
    favorite_one_week = Favorite.where(created_at: from...to)
    @rank = Entry.find(favorite_one_week.group(:entry_id).order('count(entry_id) desc').limit(5).pluck(:entry_id))
  end

  def show
    @entry = Entry.find(params[:id])
  end

  def rank
    @rank = Entry.find(Favorite.group(:entry_id).order('count(entry_id) desc').limit(5).pluck(:entry_id))
  end

  private

  def set_blog
    @blog = Blog.find(params[:id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_entry
  def create
    @favorite = Favorite.create(user_id: current_user.id, entry_id: params[:entry_id])
    @favorites = Favorite.where(entry_id: params[:entry_id])
    @entry.reload
  end

  def destroy
    favorite = Favorite.find_by(user_id: current_user.id, entry_id: params[:entry_id])
    favorite.destroy
    @favorites = Favorite.where(entry_id: params[:entry_id])
    @entry.reload
  end

  private

  def set_entry
    @entry = Entry.find(params[:entry_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:about, :top]

  def top
  end

  def about
  end

  def index
    @user = current_user
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @favorite_entries = Favorite.where(user: @user).page(params[:page]).reverse_order
    @favorite = Favorite.find_by(user_id: current_user.id, entry_id: params[:entry_id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def destroy
    @user = current_user
    @users = User.find(params[:id])
    @users.destroy
    if current_user.admin == true

      redirect_to users_path
    else
      redirect_to root_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.name %></td>
        <td><%= blog.url %></td>
        <td><%= blog.description %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @blog.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @blog.url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @blog.description %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/entries/index.html.erb
<!-- 記事一覧 -->
<main>
  <div class="col-xs-8">
    <h3 class="entry-item">新着記事</h3>
      <% @entries.each do |entry| %>
        <td><div class="panel panel-default">
          <div class="panel-body">
            <%= link_to entry.title, entry,class: "panel-body" %> - <i> published <%= time_ago_in_words(entry.published) %> ago.</i>
            <div id="likes_buttons_<%= entry.id %>">
    	       <%= render partial: 'favorites/favorite', locals: { blog_entry: entry, favorites: entry.favorites} %>
    	      </div>
          </div>
        </div>
      </td>
      <% end %>
    <h2><%= paginate @entries, class:"hogehoge" %></h2>
  </div>
<!-- いいねランキング -->
  <div class="col-xs-4">
    <h3 class="entry-item">今週のいいねランキング</h3>
     <% @rank.each.with_index(1) do |rank, i| %>
      <td><div class="panel panel-default">
            <div class="panel-body">
              <%= "第#{i}位" %>
                <%= link_to rank.title, rank,class: "panel-body" %> - <i> published <%= time_ago_in_words(rank.published) %> ago.</i>
                  <div id="likes_buttons_<%= rank.id %>">
                    <%= render partial: 'favorites/favorite', locals: { blog_entry: rank, favorites: rank.favorites} %>
                  </div>
            </div>
          </div>
      </td>
     <% end %>
  </div>
</main>

app/views/entries/show.html.erb
<div class="container">
  <h3><%= link_to @entry.title, @entry.url %></h3>
  	<i>published on <%= @entry.published %> by <%= @entry.author %></i>
		<p>
		<%= @entry.content %>
		</p>
</div>

app/views/favorites/_favorite.html.erb
<% if user_signed_in? %>

  <% unless blog_entry.favorite_user(current_user.id).blank? %>

    <%= link_to blog_entry_favorite_path(entry_id: blog_entry.id ,blog_id: blog_entry.blog_id,id:blog_entry.favorites[0].id), method: :delete, remote: true do %>
      <div class="vertical_like">
        <i class="material-icons red-text">favorite</i>
        <span class="red-text">
          <%= blog_entry.favorites_count %>
        </span>
      </div>
    <% end %>

  <% else %>

    <%= link_to blog_entry_favorites_path(entry_id: blog_entry.id ,blog_id: blog_entry.blog_id), method: :post, remote: true do %>
      <div class="vertical_like">
        <i class="material-icons grey-text text-darken-2">favorite_border</i>
        <span class="grey-text text-darken-2">
          <%= blog_entry.favorites.count %>
        </span>
      </div>
    <% end %>
  <% end %>

<% else %>



  <% if blog_entry.favorites.count > 0 %>
    <div class="vertical_like hoge">
      <i class="material-icons grey-text text-darken-2">
        <%= link_to new_user_session_path,class: "guest-heart" do %>
        favorite_border
        <% end %>
      </i>
      <span class="grey-text text-darken-2">
        <%= blog_entry.favorites.count %>
      </span>
    </div>

  <% else %>
    <div class="vertical_like hoge">
      <i class="material-icons grey-text text-darken-2">
        <%= link_to new_user_session_path,class: "guest-heart" do %>
        favorite_border
        <% end %>
      </i>
      <span class="grey-text text-darken-2">
        <%= blog_entry.favorites.count %>
      </span>
    </div>
  <% end %>


<% end %>

app/views/favorites/create.js.erb
$('#likes_buttons_<%= @entry.id %>').html("<%= j(render partial: 'favorites/favorite', locals: { blog_entry: @entry, favorites: @entry.favorites}) %>");

app/views/favorites/destroy.js.erb
$('#likes_buttons_<%= @entry.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {blog_entry: @entry, favorites: @entry.favorites}) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tottoki</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

     <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

     <link href="https://fonts.googleapis.com/css?family=Charm|Kosugi+Maru&display=swap" rel="stylesheet">

     <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">

     <meta name="viewport" content="width=device-width, initial-scale=1" />

     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" >

     <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="wrapper">

        <span><%= link_to entries_path do %>
          <%= image_tag "logo.png",style: "width: 120px; height: 50px; margin-top: 20px;" %>
          <% end %>
        </span>

        <div class="menu-trigger" href="">
            <span></span>
            <span></span>
            <span></span>
        </div>

        <nav>
            <ul>

            <% if user_signed_in? && current_user.admin? %>

                <li class="header-right">
                    <%= link_to 'my page', user_path(current_user.id) %>
                </li>
                <br>
                <li class="header-right">
                    <%= link_to "all user", users_path %>
                </li>
                <br>
                <li class="header-right">
                    <%= link_to "log out", destroy_user_session_path, method: :delete %>
                </li>

            <% elsif user_signed_in? && !current_user.admin? %>

                <li class="header-right">
                    <%= link_to "about", about_path %>
                </li>
                <br>
                <li class="header-right">
                    <%= link_to 'my page', user_path(current_user.id) %>
                </li>
                <br>
                <li class="header-right">
                    <%= link_to "log out", destroy_user_session_path, method: :delete %>
                </li>

            <% else %>

                <li class="header-right">
                    <%= link_to "about", about_path %>
                </li>
                <br>
                <li class="header-right">
                    <%= link_to "sign up", new_user_registration_path %>
                </li>
                <br>
                <li class="header-right">
                    <%= link_to "log in", new_user_session_path %>
                </li>

            <% end %>
            </ul>
        </nav>
        <div class="overlay"></div>
    </div>
    <%= yield %>
    <div class="footer">
        <div id="button"></div>
            <div id="container">
                <div id="cont">
                    <div class="footer_center">
                        <h3>kamimu</h3>
                    </div>
                </div>
            </div>
        </div>
  </body>
</html>

app/views/users/about.html.erb
<main>
	<div class="about">
		<div class="top-item-about">
			<h2 class="top-title-about">What's Tottoki!</h2>
				<p class="moji-about">Tottoki!とは大事な情報だけとっとき！</p><br>
				<p class="moji-about">ってな感じの美容情報サイトです</p><br>
				<p class="komoji-about">
				（"とっとき"は福岡では"とっておきなさい"の意味です）</p><br>
				<p class="moji-about">さまざまな記事の中、気になるものはログイン後いいねができます</p><br>
				<p class="moji-about">ログイン後にいいねした記事はマイページにて表示されます</p><br>
				<p class="moji-about">
				それでは、Let's　Tottoki～～!!!!</p><br>
				<p><a class="link-btn"><%= link_to "のぞいてみる", entries_path,class:"demo1" %></a></p>
		</div>
	</div>
</main>

app/views/users/edit.html.erb
<div class="main-sign">
  <p class="sign" align="center">
  profile</p>
	<% if @user.errors.any? %>
        <div class="alert alert-warning">
          　<ul>
            	<% @user.errors.full_messages.each do |message| %>
            	<li><%= message %></li>
            	<% end %>
          </ul>
        </div>
  <% end %>

    <div class="form1">

    <%= form_for(@user) do |f| %>

	        <%= f.attachment_field :profile_image, class: "un",placeholder:"Username" %>

	        <%= f.text_field :username, autofocus: true, autocomplete: "username", class: "un",placeholder:"Username" %>

          <%= f.text_field :email, autofocus: true, autocomplete: "email", class: "un",placeholder:"Email" %>

          <%= f.text_field :phone_number, autofocus: true, autocomplete: "phone_number", class: "un",placeholder:"phone_number" %>

		      <%= f.submit "編集", class: "submit" %>
	  <% end %>

	  </div>
</div>

app/views/users/index.html.erb
<h1 class="title-moji">All User</h1>
    <table class="table table-hover table-inverse">
        <thead>
          　　<tr>
            	<th><h2>image</h2></th>
            	<th><h2>name</h2></th>
          　　</tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
         　　 <tr>
      	      　<td><h4><%= attachment_image_tag user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-img", format: 'jpeg', fallback: "oshibana.jpg"  %></h4></td>

      	      　<td><h4><%= user.username %></h4></td>

      	      　<td><h4><%= link_to 'マイページ' , user_path(user.id), class: "btn btn-default btn-sm" %></h4></td>

      	      <% if current_user && current_user.admin? %>
      	        	<td><%= link_to "編集", edit_user_path(user.id), class: "btn btn-default btn-sm" %></td>
      	      <% end %>

      	      <% if current_user && current_user.admin? %>
      		    	  <td><%= link_to "退会", user_path(user.id, :user => {:deleted => 'true'}), method: :delete, class: "btn btn-default btn-sm", "data-confirm" => "本当に消しますか？" %></td>

              <% end %>
            </tr>
        <% end %>
        </tbody>
    </table>

app/views/users/show.html.erb
<!-- ユーザー情報 -->
<main>
	<div class="col-xs-3">
		<h1 class="title-moji">My page</h1>

			<%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-img", format: 'jpeg', fallback: "oshibana.jpg" %>

				<table class="table">
        			<tbody>
          				<tr>
							<th class="username"><%= @user.username %></th>
						</tr>
						<tr>
							<th><%= link_to "新着記事一覧ページ", entries_path(current_user.id), class: "simple_square_btn3" %></th>
						</tr>
						<tr>
							<th><%= link_to "ユーザー情報の編集", edit_user_path(current_user.id), class: "simple_square_btn3" %></th>
						</tr>
						<tr>
							<th><%= link_to "退会する", user_path(@user.id, :user => {:deleted => 'true'}), method: :delete, class: "simple_square_btn3", "data-confirm" => "本当に退会しますか？" %></th>
						</tr>
					</tbody>
				</table>
	</div>

<!-- ユーザーのお気に入り一覧 -->
	<div class="col-xs-9">
  		<h1 class="title-moji">My favorite</h1>
			<% @favorite_entries.each do |fav| %>
				<td><div class="panel panel-default">
    					<div class="panel-body">
      						<%= link_to fav.entry.title, fav.entry,class: "panel-body" %> - <i> published <%= time_ago_in_words(fav.entry.published) %> ago.</i>
    						<div id="likes_buttons_<%= fav.entry.id %>">
    							<%= render partial: 'favorites/favorite', locals: { blog_entry: fav.entry, favorites: fav.entry.favorites} %>
    						</div>
						</div>
					</div>
				</td>
			<% end %>
			<h2><%= paginate @favorite_entries, class:"hogehoge" %></h2>
	</div>
</main>

app/views/users/top.html.erb
<div class="top-page">
	<div id="vegas">
		<div class="top-item">
			<h2 class="top-title">Tottoki!</h2>
				<p class="moji">～美容系情報サイト!～</p>

					<p><a class="link-btn"><%= link_to "Tottoki!って？", about_path,class:"demo1" %></a></p><br>

					<p><a class="link-btn"><%= link_to "のぞいてみる！", entries_path,class:"demo1" %></a></p>
		</div>
	</div>
</div>